// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloService.proto

// Protobuf Java Version: 4.26.0
package com.vang.customerservice.query;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.vang.customerservice.query.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string token = 1;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <code>string token = 1;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
