FROM openjdk:17-oracle
LABEL authors="vangv"
COPY target/authcustomerservice-0.0.1-SNAPSHOT.jar authcustomerservice-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "authcustomerservice-0.0.1-SNAPSHOT.jar"]