#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: brand-service
#          uri: http://192.168.160.1:9001
#        - predicates:
#            - Path = /api/v1/brands/
#        - id: customer-service
#          uri: http://192.168.160.1:9002
#        - predicates:
#            - Path = /api/v1/customers/
#        - id: auth-customer-service
#          uri: http://192.168.160.1:8001
#        - predicates:
#            - Path = /api/v1/auth-customer/
