spring:
  application:
           name: apigateway
  cloud:
    gateway:
      routes:
        #Service
        - id: brand-service
          uri: http://192.168.160.1:9001
          predicates:
            - Path=/api/v1/brands/**
        - id: customer-service
          uri: http://192.168.160.1:9002
          predicates:
            - Path=/api/v1/customers/**
        - id: admin-service
          uri: http://192.168.160.1:9003
          predicates:
            - Path=/api/v1/admins/**
        - id: category-service
          uri: http://192.168.160.1:9006
          predicates:
            - Path=/api/v1/categories/**
        - id: seller-service
          uri: http://192.168.160.1:9007
          predicates:
            - Path=/api/v1/sellers/**
        - id: product-service
          uri: http://192.168.160.1:9008
          predicates:
            - Path=/api/v1/products/**
        - id: cart-service
          uri: http://192.168.160.1:9009
          predicates:
            - Path=/api/v1/carts/**
        - id: address-service
          uri: http://192.168.160.1:9010
          predicates:
            - Path=/api/v1/addresses/**
        - id: order-service
          uri: http://192.168.160.1:9011
          predicates:
            - Path=/api/v1/orders/**
        - id: confirm-order-service
          uri: http://192.168.160.1:9012
          predicates:
            - Path=/api/v1/confirm-orders/**
        #Auth
        - id: auth-customer
          uri: http://192.168.160.1:8001
          predicates:
            - Path=/api/v1/auth/customer/
        - id: auth-seller
          uri: http://192.168.160.1:8003
          predicates:
            - Path=/api/v1/auth/seller/
        - id: auth-admin
          uri: http://192.168.160.1:8002
          predicates:
            - Path=/api/v1/auth/admin/
server:
  port: 9000