// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloService.proto
// Protobuf Java Version: 4.26.0

package com.vang.customerservice.query.service;

public final class HelloServiceOuterClass {
  private HelloServiceOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 0,
      /* suffix= */ "",
      HelloServiceOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_vang_customerservice_query_service_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_vang_customerservice_query_service_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_vang_customerservice_query_service_HelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_vang_customerservice_query_service_HelloResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022HelloService.proto\022&com.vang.customers" +
      "ervice.query.service\"\033\n\014HelloRequest\022\013\n\003" +
      "jwt\030\001 \001(\t\"\036\n\rHelloResponse\022\r\n\005token\030\001 \001(" +
      "\t2\204\001\n\014HelloService\022t\n\005hello\0224.com.vang.c" +
      "ustomerservice.query.service.HelloReques" +
      "t\0325.com.vang.customerservice.query.servi" +
      "ce.HelloResponseB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_vang_customerservice_query_service_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_vang_customerservice_query_service_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_vang_customerservice_query_service_HelloRequest_descriptor,
        new java.lang.String[] { "Jwt", });
    internal_static_com_vang_customerservice_query_service_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_vang_customerservice_query_service_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_vang_customerservice_query_service_HelloResponse_descriptor,
        new java.lang.String[] { "Token", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
