// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloService.proto
// Protobuf Java Version: 4.26.0

package com.vang.customerservice.query.service.grpc;

public final class HelloServiceOuterClass {
  private HelloServiceOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 0,
      /* suffix= */ "",
      HelloServiceOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_vang_customerservice_query_service_grpc_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_vang_customerservice_query_service_grpc_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_vang_customerservice_query_service_grpc_HelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_vang_customerservice_query_service_grpc_HelloResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022HelloService.proto\022+com.vang.customers" +
      "ervice.query.service.grpc\"\033\n\014HelloReques" +
      "t\022\013\n\003jwt\030\001 \001(\t\"\036\n\rHelloResponse\022\r\n\005token" +
      "\030\001 \001(\t2\216\001\n\014HelloService\022~\n\005hello\0229.com.v" +
      "ang.customerservice.query.service.grpc.H" +
      "elloRequest\032:.com.vang.customerservice.q" +
      "uery.service.grpc.HelloResponseB\002P\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_vang_customerservice_query_service_grpc_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_vang_customerservice_query_service_grpc_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_vang_customerservice_query_service_grpc_HelloRequest_descriptor,
        new java.lang.String[] { "Jwt", });
    internal_static_com_vang_customerservice_query_service_grpc_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_vang_customerservice_query_service_grpc_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_vang_customerservice_query_service_grpc_HelloResponse_descriptor,
        new java.lang.String[] { "Token", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
