// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloService.proto

// Protobuf Java Version: 4.26.0
package com.vang.customerservice.query.service.grpc;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.vang.customerservice.query.service.grpc.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string jwt = 1;</code>
   * @return The jwt.
   */
  java.lang.String getJwt();
  /**
   * <code>string jwt = 1;</code>
   * @return The bytes for jwt.
   */
  com.google.protobuf.ByteString
      getJwtBytes();
}
